data:
  fraud_ratio: 0.01
description: XGBoost with default params
model: xgboost
models:
  lightgbm:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
  random_forest:
    max_depth: 10
    n_estimators: 100
    random_state: 42
  xgboost:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
project:
  entity: null
  name: fraud-detection
training:
  cv_folds: 5
  save_model: true
  scoring:
  - precision
  - recall
  - f1
  - roc_auc
wandb:
  log_artifacts: true
  log_confusion_matrix: true
  log_model: true
